//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JqGridMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athlete
    {
        public int AthleteID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Country { get; set; }
        public string Sport { get; set; }
        public Nullable<int> Gold { get; set; }
        public Nullable<int> Silver { get; set; }
        public Nullable<int> Bronze { get; set; }
        public Nullable<int> TotalMedals { get; set; }
    }
}
